name: if 조건 연습
on:
  push:
    branches:
      - develop
      - main

jobs:
  if-test:
    runs-on: ubuntu-latest
    steps:
      - name: develop 브랜치일 때만 실행
        if: github.ref == 'refs/heads/develop'
        run: echo "develop 브랜치에서만 실행됩니다. Staging 환경에 배포합니다."

      - name: main 브랜치일 때만 실행
        if: github.ref == 'refs/heads/main'
        run: echo "main 브랜치에서만 실행됩니다. Production 환경에 배포합니다."
